# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'CI'

on: [pull_request]
    
env:     
  SOLUTION_NAME: FFF.MimeTypes.sln                
  ROOT_PARH: ./FFF.MimeTypes
  CONFIGURATION: Release
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: windows-latest
      
    steps:  
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_NAME }}
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_NAME }} --no-restore 
      env:
        Configuration: ${{ env.CONFIGURATION }}
        
